CREATE TABLE [dbo].[A]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[ISO] NVARCHAR(3) NOT NULL,
	[Name] NVARCHAR(64) NOT NULL,
	CONSTRAINT [PK_A] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [UQ_A_ISO] UNIQUE ([ISO] ASC)
)
