CREATE TABLE [dbo].[B]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[TextTemplate] NTEXT NOT NULL,
	[DateAndTime] DATETIME2 NOT NULL CONSTRAINT [DF_B_DateAndTime] DEFAULT(GETDATE()),
	[DId] INT NOT NULL,
	CONSTRAINT [PK_B] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_B_D] FOREIGN KEY ([DId]) REFERENCES [dbo].[D] ([Id])
)
