CREATE TABLE [dbo].[F]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[EId] INT NOT NULL,
	[DId] INT NOT NULL,
	CONSTRAINT [PK_F] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_F_E] FOREIGN KEY ([EId]) REFERENCES [dbo].[E] ([Id]),
	CONSTRAINT [FK_F_D] FOREIGN KEY ([DId]) REFERENCES [dbo].[D] ([Id])
)
