CREATE TABLE [dbo].[E]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[DId] INT NOT NULL,
	[AId] INT NOT NULL,
	[Name] NVARCHAR(64) NOT NULL,
	CONSTRAINT [PK_E] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_E_D] FOREIGN KEY ([DId]) REFERENCES [dbo].[D] ([Id]),
	CONSTRAINT [FK_E_A] FOREIGN KEY ([AId]) REFERENCES [dbo].[A] ([Id])
)
