CREATE TABLE [dbo].[F]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[ValueDate] DATETIME2 NOT NULL,
	[Amount] DECIMAL(19,4) NOT NULL,
	[EId] INT NOT NULL,
	CONSTRAINT [PK_F] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_F_E] FOREIGN KEY ([EId]) REFERENCES [dbo].[E] ([Id])
)
