CREATE TABLE [dbo].[D]
(
	[Id] INT NOT NULL IDENTITY(1,1),
	[AId] INT NOT NULL,
	[BId] INT NOT NULL,
	CONSTRAINT [PK_D] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_D_A] FOREIGN KEY ([AId]) REFERENCES [dbo].[A] ([Id]),
	CONSTRAINT [FK_D_B] FOREIGN KEY ([BId]) REFERENCES [dbo].[B] ([Id])
)
